### ISSUE TITLE
Global death map color scaling

### ISSUE THREAD

**Issue by nfarabullini** [miraisolutions/Covid19#119]
It is ab it hard to distinguish among the different shades of grey when there is a high number of deaths in a country.

It might be more useful to enlarge/differentiate the scale of coloring for e.g. between 1,000 and 1,000,000

**Comment by GuidoMaggio** [comment]
Scales and colors have been improved in the continent page and its maps.
It would be sufficient to utilise these utilities in the global map

**Comment by GuidoMaggio** [comment]
Improved now with #55
