### ISSUE TITLE
Fix aesthetics

### ISSUE THREAD

**Issue by fvitalini** [miraisolutions/Covid19#19]
- [ ]  fonts are too big and we must find a way to say 10000, like 10k, to adjust also the names in X and Y (to be checked in other sites)

- [x] more space between first row of bar plots and second row of bar plots in the country tab

- [x]  lines in plot are perhaps too thick --> related to plotly

- [x]  Date can be removed from x axis in plots

- [x]   mouse over does not work too well, also too many options  --> related to plotly

- [x]  improve colors

**Comment by GuidoMaggio** [comment]
- [ ]  fonts are too big and we must find a way to say 10000, like 10k, to adjust also the names in X and Y (to be checked in other sites)

I believe this is the only point left open
