### ISSUE TITLE
new Swiss tab

### ISSUE THREAD

**Issue by fvitalini** [miraisolutions/Covid19#20]
swiss data available here https://github.com/openZH/covid_19
for the time being it is only about the new cases, no info about deaths or recovered

**Comment by GuidoMaggio** [comment]
Swiss data can be now taken from COVID19 package. With #115 Level 2 Cantonal data are now displayed in Country Page.
We can separate Switzerland in a new tab and remove it from Country tab which should have a new default (say USA).

Map Sp object can be found in leaflet package. To check

**Comment by GuidoMaggio** [comment]
Used Map leaflet::gadmCHE
There are no other maps available in leaflet, only Switzerland

In the Country page the default country is picked USA
