### ISSUE TITLE
add info map pop-up

### ISSUE THREAD

**Issue by fvitalini** [miraisolutions/Covid19#55]
when clicking on the map, the pop up should show more information, namely:
- Country
- Confirmed
- Deaths
- Active
- Recovered
- (Growth rate)
- (Death rate)

**Comment by GuidoMaggio** [comment]
This can be now easily achieved using utilities developed in #92 
map_popup_data

**Comment by GuidoMaggio** [comment]
Update global page with utilities from continents page and maps

**Comment by GuidoMaggio** [comment]
Added features from continent maps.
absolutePanel transparent
Swapped orange and yellow colour in sccatterplot
