### ISSUE TITLE
Remove pop-up disclaimer

### ISSUE THREAD

**Issue by gabrielfoix** [miraisolutions/Covid19#61]
Remove pop-up disclaimer and, instead, add the same information in the header.
Preferable solution: A pop-up message whenmousing over the subtitle.

**Comment by fvitalini** [comment]
README needs to be updated as well

**Comment by gabrielfoix** [comment]
Pushed the first version.
@fvitalini Please review the text on the readme as well as the solution with the tooltip.

**Comment by GuidoMaggio** [comment]
@fvitalini, I believe this ticket is done and already live.
correct? can you please close if so?
