### ISSUE TITLE
Colour scale and legend in over 1M case not correct

### ISSUE THREAD

**Issue by GuidoMaggio** [miraisolutions/Covid19#79]
In the world map if I check "Confirmed" cases I have a color scale from 1 to 10 millions.
If then I click on "per 1M pop" then I still have scale from  1 to 10 millions. 
i.e. max 10 million cases over a million population.
The colors seem in fact much lighter.
The scale should go possibly from 1 to 10000 (guess)

The same happens for all the variables, in particular those "New".

To check also if perhaps we are still considering small countries like San Marino that would mess up the color scale

**Comment by fvitalini** [comment]
replace data_clean() with data_plot() in  https://github.com/miraisolutions/Covid19/blob/master/R/mod_map.R line 122
