### ISSUE TITLE
lineplot: rolling weekly average - remove dots

### ISSUE THREAD

**Issue by GuidoMaggio** [miraisolutions/Covid19#80]
![image](https://user-images.githubusercontent.com/13679154/81538281-d6580600-936e-11ea-9d45-416f89ee74ba.png)

LIneplot  from day of 1000 contagion 

1)
For some variables are the lines do not look too good. Say attached pic:
looking bad: New Confirmed, New Active
partially affected: growth factor, lethality rate
looking ok: the rest

If doing a rolling average for only 2 variables could create problems then it can be done for all.

Rolling average in day X: mean(Day(x)..... Day(x-7))

2) 
Remove also dots and keep only line plot.
Despite I like the dots initially now that we have more days they make the plot harder to read.
Alternative could be to have a dot every 7 days

**Comment by fvitalini** [comment]
check package zoo

**Comment by fvitalini** [comment]
https://github.com/miraisolutions/Covid19/blob/master/R/mod_compare_nth_cases_plot.R
line 59

**Comment by fvitalini** [comment]
for the dots in function plot_all_highlight remove the geom_point (line 463)
